[package]
name = "euler-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gkquad = "0.0.4"
tiny-skia = "0.11.2"
